const products = [
  {
    id: 1,
    reference: "PRD1",
    label: "produit 1",
    qty: 10,
    price: 20,
    is_gift: true,
    gift_price: 15,
  },
  {
    id: 2,
    reference: "PRD",
    label: "produit 2",
    qty: 10,
    price: 20,
    is_gift: true,
    gift_price: 15,
  },
  {
    id: 3,
    reference: "PRD",
    label: "produit 3",
    qty: 10,
    price: 20,
    is_gift: false,
    gift_price: 15,
  },
  {
    id: 4,
    reference: "PRD",
    label: "produit 4",
    qty: 10,
    price: 20,
    is_gift: false,
    gift_price: 15,
  },
  {
    id: 5,
    reference: "PRD",
    label: "produit 5",
    qty: 10,
    price: 20,
    is_gift: true,
    gift_price: 15,
  },
  {
    id: 6,
    reference: "PRD",
    label: "produit 6",
    qty: 10,
    price: 20,
    is_gift: true,
    gift_price: 15,
  },
];

export default products;
